somef package/src/somef/cli.py

Made the code throw an exception instead of doing sys.exit in one place (since I want to be able to handle those errors myself) and made it so the classifiers do not run if the array of excerpts is empty (this was causing a crash)

bug fixes (see description)

---

somef package/src/somef/cli.py
somef package/src/somef/configuration.py
somef package/src/somef/header_analysis.py
somef package/src/somef/schema/software_schema.py

I instead handled lots of the errors by either omitting the data that was missing or by throwing an excepting that could be caught by a script (rather than causing the script to terminate via a sys.exit)

Fixed bugs and removed many sys.exits

---

src/somef/cli.py
src/somef/header_analysis.py
src/somef/test/test_cli.py
src/somef/test/test_header_analysis.py

Added more tests and the ability to detect identifiers if Zenodo badges are used. They won't resolve to the DOI, but at least it is possible to get an identifier for a repository

Fix #78, Fix #114

---

README.md
docs/install.md
src/somef/cli.py
src/somef/header_analysis.py
src/somef/test/test_cli.py

Solves links to executable examples (Binder) and also extracts the long name of the title

Binder links

---

src/somef/cli.py
src/somef/header_analysis.py
src/somef/test/test_header_analysis.py

Fixed errors that could lead to an exception when parsing headers. Also now if headers are combined (== and ##, we only parse the one with a majority)
Fixed an error that made no classifiers be run when the header extraction failed.

Improved robustness to errors in header extraction

---

README.md
docs/install.md

Added instructions for running through Docker

---

src/somef/cli.py

This works by downloading an archive of the repository from GitHub. It is actually surprisingly quick, and much faster than when I tried to do this via git cloning. It downloading the main branch if no branch is specified, but can also do a specific commit if that is given.
I am not sure how to proceed with adding these files to the somef output, so for now they are just printed to the console.
Please let me know how you think they should be incorporated into the output.

Added discovery of dockerfiles and notebooks

---

src/somef/header_analysis.py
src/somef/test/test_header_analysis.py

Fixed issues:
- 139, 89: removing call to clean_html method in header_analysis.extract_categories_using_headers
- 231: creating method extract_bash_code to use it in header_analysis.extract_header_content

Fixed issues 139, 89 and 231

---

src/somef/cli.py

Added method remove_bibtex to solve issue 249

Fixed issue 249

---

src/somef/cli.py
src/somef/test/test_cli.py

Added new feature from issue 166. Added acknowledgments from file in repository, when present, to results

Added acknowledgments from files to results

---

src/somef/test/test_cli.py

Fixed tests:
- test_extract_bibtext
- test_extract_title_underline
- test_issue_211
- test_issue_224

Fixed tests as indicated in issue #295

---

pyproject.toml
setup.py

Added pyproject.toml file needed for packaging process. Updated dependency versions on setup.py

Added pyproject.toml file and updated steup.py

---

src/somef/test/test_data/export_test.json

Adding missing json test file due to gitignore

---

pyproject.toml
src/somef/export/turtle_export.py

updated apply_mapping and correct wrong version

---

pyproject.toml
src/somef/export/turtle_export.py

In case data parameter be a path instead a dictionary

Updated turtle_export/ apply_mapping

---

src/somef/export/json_export.py
src/somef/test/test_codemeta_gitlab_export.py

Descripion and url had problem with gitlab and other repos. BuildInstruccions just with categoryy insltatioin. Not documentation

Resolve problem in codemeta export and buildinstrucctions. Fixes #677

---

src/somef/process_repository.py
src/somef/somef_cli.py
src/somef/test/test_gitlab_selfhosted.py

process to allow repositories from gitlab self hosted. Not just gitlab.com

New process and test to chek gitlab selfhosted. Fixes #687

---

src/somef/export/json_export.py
src/somef/test/test_codemeta_export.py

Improve codemeta exports with releaseNotes and last version. Test export code…meta to check if realeaseNotes exist and spdx

Improve codemeta  export. Fixes #678

---

src/somef/export/json_export.py
src/somef/utils/constants.py

Software requirements with name and version or array of string.  Fixes #754,#755

---

src/somef/export/json_export.py
src/somef/parser/authors_parser.py
src/somef/parser/python_parser.py
src/somef/process_files.py
src/somef/test/test_codemeta_export.py
src/somef/utils/constants.py

Extract authors from authors file. Test extract author. Fixes #566
